apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
specs:
  replicas: 2
  selector:
    matchLables:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    specs:
      containers:
        - name: nodeapp
          image: khantki/simple-todo-app:main
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec: 
  selector:
    app: nodeapp
  ports:
  - name:  Node App Port
    port:  3000
    protocol: TCP
    targetPort: 3000