apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
specs:
  replicas: 3
  selector:
    matchLables:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    specs:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec: 
  selector:
    app: mongodb
  ports:
  - name:  MongoDB Port
    port:  8000
    protocol: TCP
    targetPort: 27017